language: r
os: linux
cache: packages
dist: trusty

r_packages:
  - covr

r:
  - release
  - devel

after_success:
- Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never
